### ISSUE TITLE
Unit test files are missing in release tarball

### ISSUE THREAD

**Issue by cgzones** [TresysTechnology/selint#11]
In the release tarball https://github.com/TresysTechnology/selint/releases/download/v1.0.1/selint-1.0.1.tar.gz the sub-folders in the test directory are missing.
That prevents running the testsuite.

Also the `CHANGELOG` and `LICENSE` files are missing.

p.s.: [this](https://github.com/TresysTechnology/selint/blob/bc9e163cc7284dd08a932a975920e39ca55ed59c/src/ordering.c#L644) is probably is misspelling (`controled` -> `controlled`)

**Comment by dburgener** [comment]
Just push 96b68fa2953e303121f926a66be7c9c38a0a5e31 to fix the typo.  Other issues in progress.

**Comment by dburgener** [comment]
Fixed in 1c15fc282230e7accef57d3b124627bc667fb8ad
