### ISSUE TITLE
Enable discussions on repo?

### ISSUE THREAD

**Issue by dburgener** [TresysTechnology/selint#180]
@stevedlawrence I just got a popup from github telling me that we can enable a discussions feature so the project can have discussions without opening issues.  I think that would be a great idea for this project since we have no mailing list, but I don't seem to have the permissions to turn on that feature.  Do you think it would be helpful and if so, can you enable it?  @cgzones, your thoughts are of course welcome too.

**Comment by stevedlawrence** [comment]
Sure thing! Intersting feature. It's now enabled.

**Comment by dburgener** [comment]
Thanks!
