### ISSUE TITLE
man/selint.h2m missing in release archive

### ISSUE THREAD

**Issue by cgzones** [TresysTechnology/selint#196]
The file `man/selint.h2m` is missing in the release archive https://github.com/TresysTechnology/selint/releases/download/v1.2.0/selint-1.2.0.tar.gz .
Maybe the dist-archive was created on a system without help2man(1)?

**Comment by dburgener** [comment]
That's probably it.  I messed up the automated creation and did some steps manually.  Thanks for the report.

I'll upload a new tarball today for 1.2.0.

**Comment by dburgener** [comment]
Okay, new 1.2.0 tarball uploaded, should include man pages now.  Thanks again!
