### ISSUE TITLE
Running checks on source policy for Android (AOSP)

### ISSUE THREAD

**Issue by Johnmper** [TresysTechnology/selint#199]
Hi, first I would like to say I'm fairly new to SELinux and I'm still exploring all sorts of documentations.

- Is it possible with the current tool to check syntax of policies for Android or would changes be required?
- I can run the checks on the standalone .TE files. But can I validate if a macro really exists in the AOSP sepolicy repo?

**Comment by dburgener** [comment]
> Can I ask then if selint does any check if the permissions and classes are valid?

This should be checks E-007 and E-008, which you're getting errors on.  The behavior on locating the classes and permissions differs based on if you're building policy for use on your current system or cross-compiling. To cross-compile you want to use the -s flag with selint.  In that situation, selint looks for files named "obj_perm_sets.spt", "access_vectors" in the list of files passed for scanning and loads information from them if present (on refpolicy systems, obj_perm_sets.spt is the permission macros, and access_vectors is the permissions and classes).  I don't have Android policy in front of me at the moment to see if they ship equivalent files.  It's possible some customization may be needed for the macros in particular.  In non-source mode the same information is read from the running system and from the SELinux development headers (/usr/share/selinux/devel).  That path is unfortunately hard-coded at the moment.  I'd definitely accept a PR to make it configurable.

I'd also mention that I'd take results against Android policy with a grain of salt.  There are somewhat different standards and conventions here than for refpolicy policies and not all checks may necessarily apply.  If you were to come up with a config that works well on your Android system and wanted to share it, I'd accept a PR for a suggested Android config to help people in the future.
