### ISSUE TITLE
Support excluding entries from lists

### ISSUE THREAD

**Issue by cgzones** [TresysTechnology/selint#2]
Currently SELlint warns on

```
interface(`domain_getattr_confined_domains',`
        gen_require(`
                attribute domain, unconfined_domain_type;
        ')

        allow $1 { domain -unconfined_domain_type }:process getattr;
')
```

with `Attribute unconfined_domain_type is listed in require block but not used in interface (W-003)`

p.s.: you might want to add a check for uthash in the configure script

```
AC_CHECK_HEADER([uthash.h], [], [AC_MSG_ERROR([Unable to find uthash header])])
```

**Comment by dburgener** [comment]
Fixed in 8dc1fa34ece02a47f4e45a3627bc451f1f41c9e5 and ad16e6d98d1e41fa04e697ca340aa74ef545d1a4

Thanks for the report!
