### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by cgzones** [TresysTechnology/selint#218]
Since the Reference Policy just released a new version with the `policy_module` macro changed and thus not scan-able with the latest SELint stable release, which was issued almost one year ago, can we have a new release?
None of the open issues and pull-requests seem to be too serious to be necessarily resolved prior.

**Comment by dburgener** [comment]
I agree.  I'll make a release notes PR.

**Comment by dburgener** [comment]
I'm thinking about just calling this 1.2.1 since there don't seem to be any major new features merged since 1.2.0.  Thoughts?

**Comment by cgzones** [comment]
> I'm thinking about just calling this 1.2.1 since there don't seem to be any major new features merged since 1.2.0. Thoughts?

Agreed, mostly internal changes plus support for uncommon syntaxes.
Only user visible check related change seems to be https://github.com/TresysTechnology/selint/commit/9ae4076f3c774f2b68a6adacdd0c3d39a6dae284.

**Comment by dburgener** [comment]
#219

I dated the changelog for Monday so as to not release on a Friday afternoon.

**Comment by dburgener** [comment]
v1.2.1 released: https://github.com/TresysTechnology/selint/releases/tag/v1.2.1
